loki:
  enabled: true

promtail:
  enabled: true

grafana:
  enabled: false
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 6.3.0-beta2

prometheus:
  enabled: false
  server:
    fullnameOverride: prometheus-server
